apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleflaskprojet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleflaskprojet
  template:
    metadata:
      labels:
        app: sampleflaskprojet
    spec:
      containers:
        - name: sampleflaskprojet
          image: ayoubajdour/sampleflaskprojet:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: 8082
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sampleflaskprojet
spec:
  selector:
    app: sampleflaskprojet
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer